# Generated by Django 5.1.3 on 2024-12-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('ai_write', 'Access to ai write')]},
        ),
    ]
