# Generated by Django 5.1.3 on 2024-12-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_upload_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-upload_at']},
        ),
    ]
