# Generated by Django 5.1.3 on 2024-12-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_rating'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
            bases=('notifications.notification',),
        ),
    ]
