# Generated by Django 5.1.3 on 2024-12-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_usernotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
